[phases.setup]
nixPkgs = [
  "nodejs",
  "python311",
  "python311Packages.pip",
  "gcc",
  "ffmpeg",
  "glib",
  "nss",
  "nspr",
  "atk",
  "atk-bridge",
  "cups",
  "drm",
  "dbus",
  "xcbutilwm",
  "libxkbcommon",
  "pango",
  "cairo",
  "gtk3"
]

[start]
cmd = "cd backend && npm start"