[phases.setup]
nixPkgs = [
  "nodejs",
  "python311",
  "python311Packages.pip",
  "gcc",
  "ffmpeg",
  "glib",
  "glibc",
  "nss",
  "nspr",
  "atk",
  "atk-bridge",
  "cups",
  "drm",
  "dbus",
  "libxkbcommon",
  "gtk3",
  "pango",
  "cairo",
  "expat",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb"
]

[start]
cmd = "cd backend && npm start"